name: Upload Maven Transitive Dependencies
on: workflow_dispatch

jobs:
  build_publish:
    name: Upload Maven Transitive Dependencies

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        java-package: jdk
        distribution: microsoft

    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v4
